### ISSUE TITLE
Refresh Token Info

### ISSUE THREAD

**Issue by tomassasovsky** [lavalink-devs/youtube-source#71]
Will the refresh token expire? If so, do we know what its lifespan is? Do we have to do anything after the initial setup to keep it working indefinitely?

**Comment by devoxin** [comment]
The refresh token is not currently known to expire. It's an OAuth token so it'll likely remain valid for as long as you permit the YouTube TV app to access your account, or your account gets flagged/banned.

Once you have the token, you can keep it in operation until one of the above two conditions are met, otherwise it will remain valid indefinitely.
